version: '2'

services:
    fhem:
        restart: always
        expose:
            - "8083"
            - "7072"
        ports:
            - "8083:8083"
            - "7072:7072"
        image: michaelatdocker/fhem
        privileged: true
        volumes:
            - ./fhem/core/:/opt/fhem/
        networks:
            - fhem-network
        depends_on:
            - "mysql"
            - "mqtt"

  owncloud:
    image: owncloud
    restart: always
    expose:
        - "8080"
        - "80"
    ports:
      - "8080:8080"
      - "80:80"
    networks:
        - fhem-network
    depends_on:
        - "mysql"


  mysql:
    image: mariadb
    restart: always
    expose:
        - "3306"
        - "33060"
    ports:
        - "3306:3306"
        - "33060:33060"
    networks:
        - fhem-network
    environment:
      MYSQL_ROOT_PASSWORD: example

    mqtt:
        restart: always
        expose:
            - "1883"
            - "9001"
        ports:
            - "1883:1883"
            - "9001:9001"
        image: toke/mosquitto
        networks:
            - fhem-network
        volumes:
            - ./mqtt/config/:/mqtt/config/
            - ./mqtt/log/:/mqtt/log/
            - ./mqtt/data/:/mqtt/data/

    nodered:
        restart: always
        expose:
            - "1880"
        ports:
            - "1880:1880"
        image: nodered/node-red-docker:0.18.4
        volumes:
            - ./nodered/data/:/data/
        networks:
            - fhem-network
        depends_on:
            - "mqtt"
            
    pyload:
        restart: always
        expose:
            - "8000"
        ports:
            - "8000:8000"
        image: writl/pyload:latest
        volumes:
            -  /opt/pyload/Downloads:/opt/pyload/Downloads
            -  /opt/pyload/Downloads:/opt/pyload/pyload-config
        networks:
            - fhem-network
        depends_on:
            - "mqtt"    
            

networks:
    fhem-network:
        driver: bridge
